/**
 * Customer Flow Scenario
 * Сценарий обучения: создание заявки на перевозку
 */

import type { TutorialStep } from './types'

export const steps: TutorialStep[] = [
  // === Навигация через меню ===
  {
    id: 'open_menu',
    title: 'Откройте меню',
    description: 'Нажмите на кнопку меню в левом верхнем углу, чтобы открыть навигацию.',
    target: 'mobile-menu-btn',
    tooltipPosition: 'right',
    completionType: 'action',
    completionAction: 'menu:opened',
  },
  {
    id: 'select_requests',
    title: 'Выберите "Заявки"',
    description: 'В открывшемся меню нажмите на пункт "Заявки", чтобы перейти к списку заявок на перевозку.',
    target: 'mobile-nav-requests',
    tooltipPosition: 'right',
    completionType: 'navigate',
    completionAction: '/',
  },
  // === Создание заявки ===
  {
    id: 'customer_start',
    title: 'Создание заявки',
    description: 'Теперь вы в разделе "Заявки". Нажмите кнопку "Новая заявка" чтобы создать заявку на перевозку.',
    target: 'create-request-btn',
    tooltipPosition: 'bottom',
    completionType: 'navigate',
    completionAction: '/freight-requests/new',
  },
  // === Детальный туториал маршрута (7 шагов) ===
  {
    id: 'route_loading_point',
    title: 'Точка погрузки',
    description: 'Первая точка маршрута — это всегда место погрузки. Выберите страну и город откуда нужно забрать груз.',
    hint: 'Синяя полоска слева означает погрузку',
    target: 'route-point-0',
    tooltipPosition: 'top',
    completionType: 'action',
    completionAction: 'route:citySelected',
  },
  {
    id: 'route_date_range',
    title: 'Дата погрузки',
    description: 'Укажите дату погрузки. Можно указать промежуток дат (с ... по ...) если точная дата неизвестна. Второе поле опционально.',
    target: 'route-date-fields',
    tooltipPosition: 'bottom',
    completionType: 'action',
    completionAction: 'route:dateSet',
  },
  // --- Опциональные поля: Время ---
  {
    id: 'route_add_time',
    title: 'Добавить время',
    description: 'Можно указать время погрузки. Нажмите "+ Время".',
    target: 'route-add-time',
    tooltipPosition: 'top',
    completionType: 'action',
    completionAction: 'route:timeToggled',
    skippable: true,
  },
  {
    id: 'route_time_added',
    title: 'Поле времени добавлено',
    description: 'Появилось поле для указания времени (с ... по ...). Справа есть кнопка "Убрать" — она удалит это поле.',
    target: 'route-time-section',
    tooltipPosition: 'top',
    completionType: 'manual',
    skippable: true,
  },
  {
    id: 'route_hide_time',
    title: 'Убрать время',
    description: 'Попробуйте убрать поле времени. Нажмите "Убрать".',
    target: 'route-hide-time',
    tooltipPosition: 'left',
    completionType: 'action',
    completionAction: 'route:timeToggled',
    skippable: true,
  },
  // --- Опциональные поля: Контакт ---
  {
    id: 'route_add_contact',
    title: 'Добавить контакт',
    description: 'Можно указать контактное лицо на погрузке. Нажмите "+ Контакт".',
    target: 'route-add-contact',
    tooltipPosition: 'top',
    completionType: 'action',
    completionAction: 'route:contactToggled',
    skippable: true,
  },
  {
    id: 'route_contact_added',
    title: 'Поле контакта добавлено',
    description: 'Появились поля для имени и телефона. Кнопка "Убрать" удалит эти поля.',
    target: 'route-contact-section',
    tooltipPosition: 'top',
    completionType: 'manual',
    skippable: true,
  },
  {
    id: 'route_hide_contact',
    title: 'Убрать контакт',
    description: 'Попробуйте убрать контакт. Нажмите "Убрать".',
    target: 'route-hide-contact',
    tooltipPosition: 'left',
    completionType: 'action',
    completionAction: 'route:contactToggled',
    skippable: true,
  },
  // --- Опциональные поля: Примечание ---
  {
    id: 'route_add_comment',
    title: 'Добавить примечание',
    description: 'Можно добавить дополнительную информацию. Нажмите "+ Примечание".',
    target: 'route-add-comment',
    tooltipPosition: 'top',
    completionType: 'action',
    completionAction: 'route:commentToggled',
    skippable: true,
  },
  {
    id: 'route_comment_added',
    title: 'Примечание добавлено',
    description: 'Появилось поле для текста. Здесь можно указать особенности погрузки, пожелания и т.д.',
    target: 'route-comment-section',
    tooltipPosition: 'top',
    completionType: 'manual',
    skippable: true,
  },
  {
    id: 'route_hide_comment',
    title: 'Убрать примечание',
    description: 'Попробуйте убрать примечание. Нажмите "Убрать".',
    target: 'route-hide-comment',
    tooltipPosition: 'left',
    completionType: 'action',
    completionAction: 'route:commentToggled',
    skippable: true,
  },
  {
    id: 'route_unloading_point',
    title: 'Точка разгрузки',
    description: 'Последняя точка — место разгрузки. Заполните страну и город доставки.',
    hint: 'Зелёная полоска слева означает разгрузку',
    target: 'route-point-1',
    tooltipPosition: 'top',
    completionType: 'action',
    completionAction: 'route:citySelected',
  },
  {
    id: 'route_unloading_date',
    title: 'Дата разгрузки',
    description: 'Укажите планируемую дату доставки.',
    target: 'route-point-1',
    tooltipPosition: 'top',
    completionType: 'action',
    completionAction: 'route:dateSet',
  },
  {
    id: 'route_add_intermediate',
    title: 'Добавить промежуточную точку',
    description: 'Если нужна дозагрузка или частичная выгрузка по пути — добавьте промежуточную точку. Нажмите "Добавить точку".',
    hint: 'Для промежуточных точек можно выбрать тип: погрузка, разгрузка или оба',
    target: 'route-add-point-btn',
    tooltipPosition: 'top',
    completionType: 'action',
    completionAction: 'route:pointAdded',
    skippable: true,
  },
  {
    id: 'route_intermediate_city',
    title: 'Заполните новую точку',
    description: 'Выберите страну и город для новой точки разгрузки.',
    hint: 'Эта точка станет конечной точкой маршрута',
    target: 'route-point-2',
    tooltipPosition: 'top',
    completionType: 'action',
    completionAction: 'route:citySelected',
    skippable: true,
  },
  {
    id: 'route_intermediate_date',
    title: 'Дата разгрузки',
    description: 'Укажите планируемую дату доставки в новую точку.',
    target: 'route-date-fields-2',
    tooltipPosition: 'top',
    completionType: 'action',
    completionAction: 'route:dateSet',
    skippable: true,
  },
  {
    id: 'route_reorder',
    title: 'Изменение порядка',
    description: 'Вы можете перетащить точку за иконку слева, чтобы изменить порядок маршрута. Это опционально — продолжайте когда будете готовы.',
    hint: 'Первая точка всегда останется погрузкой, последняя — разгрузкой',
    target: 'route-points-list',
    tooltipPosition: 'top',
    completionType: 'manual',
    skippable: true,
  },
  // === Переход к следующему шагу wizard'а ===
  {
    id: 'route_continue',
    title: 'Маршрут готов!',
    description: 'Отлично! Маршрут заполнен. Нажмите "Далее" чтобы перейти к описанию груза.',
    target: 'submit-btn',
    tooltipPosition: 'top',
    completionType: 'action',
    completionAction: 'wizard:next',
  },
  // === Детальный туториал груза (6 шагов) ===
  {
    id: 'cargo_description',
    title: 'Описание груза',
    description: 'Опишите что перевозите. Например: мебель, стройматериалы, продукты питания.',
    hint: 'Чем подробнее описание, тем точнее будут предложения перевозчиков',
    target: 'cargo-description',
    tooltipPosition: 'bottom',
    completionType: 'manual',
  },
  {
    id: 'cargo_weight',
    title: 'Вес груза',
    description: 'Укажите общий вес груза в килограммах. Это обязательное поле.',
    hint: 'Если точный вес неизвестен — укажите примерный',
    target: 'cargo-weight',
    tooltipPosition: 'bottom',
    completionType: 'manual',
  },
  {
    id: 'cargo_volume',
    title: 'Объём груза',
    description: 'Укажите объём груза в кубических метрах. Поле опциональное.',
    target: 'cargo-volume',
    tooltipPosition: 'bottom',
    completionType: 'manual',
    skippable: true,
  },
  {
    id: 'cargo_dimensions',
    title: 'Габариты',
    description: 'Укажите размеры груза: длину, ширину и высоту в метрах. Поля опциональные.',
    hint: 'Важно для негабаритных грузов',
    target: 'cargo-dimensions',
    tooltipPosition: 'bottom',
    completionType: 'manual',
    skippable: true,
  },
  {
    id: 'cargo_quantity',
    title: 'Количество мест',
    description: 'Укажите количество грузовых мест (палет, коробок, единиц).',
    target: 'cargo-quantity',
    tooltipPosition: 'bottom',
    completionType: 'manual',
  },
  {
    id: 'cargo_adr',
    title: 'Класс опасности',
    description: 'Если груз относится к опасным — выберите класс ADR. Для обычных грузов оставьте "Не требуется".',
    target: 'cargo-adr',
    tooltipPosition: 'top',
    completionType: 'manual',
    skippable: true,
  },
  {
    id: 'cargo_continue',
    title: 'Груз описан!',
    description: 'Отлично! Информация о грузе заполнена. Нажмите "Далее" для перехода к требованиям к транспорту.',
    target: 'submit-btn',
    tooltipPosition: 'top',
    completionType: 'action',
    completionAction: 'wizard:next',
  },
  // === Детальный туториал транспорта ===
  {
    id: 'vehicle_type',
    title: 'Тип транспорта',
    description: 'Выберите тип транспорта (фура, тягач и т.д.). После выбора в "Тип кузова" останутся только подходящие варианты.',
    hint: 'Можно пропустить и сразу выбрать тип кузова — тип транспорта определится автоматически',
    target: 'vehicle-type',
    tooltipPosition: 'bottom',
    completionType: 'manual',
    skippable: true,
  },
  {
    id: 'vehicle_subtype',
    title: 'Тип кузова',
    description: 'Выберите тип кузова: тент, рефрижератор, контейнер и т.д. Если тип транспорта не выбран — он определится автоматически.',
    target: 'vehicle-subtype',
    tooltipPosition: 'bottom',
    completionType: 'manual',
  },
  {
    id: 'vehicle_loading',
    title: 'Тип погрузки',
    description: 'Укажите способ погрузки: задняя, боковая, верхняя. Можно выбрать несколько вариантов.',
    target: 'vehicle-loading',
    tooltipPosition: 'bottom',
    completionType: 'manual',
    skippable: true,
  },
  {
    id: 'vehicle_capacity',
    title: 'Грузоподъёмность',
    description: 'Укажите минимальную грузоподъёмность транспорта в килограммах.',
    target: 'vehicle-capacity',
    tooltipPosition: 'bottom',
    completionType: 'manual',
    skippable: true,
  },
  {
    id: 'vehicle_volume',
    title: 'Объём кузова',
    description: 'Укажите минимальный объём кузова в кубических метрах.',
    target: 'vehicle-volume',
    tooltipPosition: 'bottom',
    completionType: 'manual',
    skippable: true,
  },
  {
    id: 'vehicle_dimensions',
    title: 'Размеры кузова',
    description: 'Укажите минимальные внутренние размеры кузова: длину, ширину и высоту в метрах.',
    target: 'vehicle-dimensions',
    tooltipPosition: 'top',
    completionType: 'manual',
    skippable: true,
  },
  // === Поля для изотерма/рефрижератора (условные) ===
  {
    id: 'vehicle_temperature',
    title: 'Температурный режим',
    description: 'Для изотерма или рефрижератора можно указать требуемый температурный режим. Поставьте галочку чтобы открыть поля.',
    hint: 'Появляется только при выборе изотермического кузова или рефрижератора',
    target: 'vehicle-temperature',
    tooltipPosition: 'top',
    completionType: 'manual',
    skippable: true,
  },
  {
    id: 'vehicle_thermograph',
    title: 'Термописец',
    description: 'Термописец — устройство для записи температуры в пути. Отметьте если требуется.',
    hint: 'Появляется только при выборе изотермического кузова или рефрижератора',
    target: 'vehicle-thermograph',
    tooltipPosition: 'top',
    completionType: 'manual',
    skippable: true,
  },
  {
    id: 'vehicle_continue',
    title: 'Транспорт выбран!',
    description: 'Требования к транспорту заполнены. Нажмите "Далее" для перехода к условиям оплаты.',
    target: 'submit-btn',
    tooltipPosition: 'top',
    completionType: 'action',
    completionAction: 'wizard:next',
  },
  // === Условия оплаты (пошагово) ===
  {
    id: 'payment_price',
    title: 'Стоимость перевозки',
    description: 'Укажите желаемую стоимость перевозки.',
    target: 'payment-price',
    tooltipPosition: 'top',
    completionType: 'manual',
  },
  {
    id: 'payment_currency',
    title: 'Валюта',
    description: 'Выберите валюту для расчётов.',
    target: 'payment-currency',
    tooltipPosition: 'top',
    completionType: 'manual',
  },
  {
    id: 'payment_vat',
    title: 'НДС',
    description: 'Укажите, включён ли НДС в стоимость.',
    target: 'payment-vat',
    tooltipPosition: 'top',
    completionType: 'manual',
  },
  {
    id: 'payment_method',
    title: 'Способ оплаты',
    description: 'Выберите удобный способ оплаты.',
    target: 'payment-method',
    tooltipPosition: 'top',
    completionType: 'manual',
  },
  {
    id: 'payment_terms',
    title: 'Условия оплаты',
    description: 'Укажите, когда будет производиться оплата.',
    target: 'payment-terms',
    tooltipPosition: 'top',
    completionType: 'manual',
  },
  {
    id: 'payment_no_price',
    title: 'Можно не указывать цену',
    description: 'Если не знаете точную стоимость — отметьте галочку, и перевозчики сами предложат цену.',
    target: 'payment-no-price',
    tooltipPosition: 'bottom',
    completionType: 'manual',
    skippable: true,
  },
  {
    id: 'payment_continue',
    title: 'Оплата готова!',
    description: 'Условия оплаты заполнены. Нажмите "Далее" для перехода к проверке данных.',
    target: 'submit-btn',
    tooltipPosition: 'top',
    completionType: 'action',
    completionAction: 'wizard:next',
  },
  // === Итоговый экран ===
  {
    id: 'summary_overview',
    title: 'Проверка данных',
    description: 'Здесь подведён итог вашей заявки. Проверьте маршрут, груз, транспорт и условия оплаты.',
    hint: 'Все данные можно отредактировать, вернувшись на предыдущие шаги',
    target: 'confirmation-summary',
    tooltipPosition: 'top',
    completionType: 'manual',
  },
  {
    id: 'submit_buttons',
    title: 'Кнопки навигации',
    description: 'Нажмите "Опубликовать" чтобы разместить заявку. Кнопка "Назад" позволяет вернуться к редактированию.',
    target: 'wizard-buttons',
    tooltipPosition: 'top',
    completionType: 'manual',
  },
  {
    id: 'customer_submit_request',
    title: 'Опубликовать заявку',
    description: 'Нажмите "Опубликовать" для размещения заявки.',
    target: 'submit-btn',
    tooltipPosition: 'top',
    completionType: 'action',
    completionAction: 'freightRequest:created',
  },
  // === Заявка опубликована ===
  {
    id: 'request_published',
    title: 'Заявка опубликована!',
    description: 'Ваша заявка появилась в списке. Теперь перевозчики могут её увидеть и сделать предложения.',
    hint: 'Когда перевозчик заинтересуется, вы получите уведомление',
    target: 'freight-request-card',
    tooltipPosition: 'bottom',
    route: '/',
    completionType: 'manual',
  },
  // === Завершение с предложением обучения ===
  {
    id: 'customer_complete',
    title: 'Что дальше?',
    description: 'Перевозчики видят вашу заявку и могут сделать предложения с ценой и условиями. Вы сможете сравнить и выбрать лучшее предложение.',
    completionType: 'manual',
    showOffersTrainingButton: true,
  },
]

export default { steps }
