// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package values

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// CountryRU is a Country of type RU.
	CountryRU Country = "RU"
	// CountryKZ is a Country of type KZ.
	CountryKZ Country = "KZ"
	// CountryBY is a Country of type BY.
	CountryBY Country = "BY"
)

var ErrInvalidCountry = fmt.Errorf("not a valid Country, try [%s]", strings.Join(_CountryNames, ", "))

var _CountryNames = []string{
	string(CountryRU),
	string(CountryKZ),
	string(CountryBY),
}

// CountryNames returns a list of possible string values of Country.
func CountryNames() []string {
	tmp := make([]string, len(_CountryNames))
	copy(tmp, _CountryNames)
	return tmp
}

// String implements the Stringer interface.
func (x Country) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Country) IsValid() bool {
	_, err := ParseCountry(string(x))
	return err == nil
}

var _CountryValue = map[string]Country{
	"RU": CountryRU,
	"KZ": CountryKZ,
	"BY": CountryBY,
}

// ParseCountry attempts to convert a string to a Country.
func ParseCountry(name string) (Country, error) {
	if x, ok := _CountryValue[name]; ok {
		return x, nil
	}
	return Country(""), fmt.Errorf("%s is %w", name, ErrInvalidCountry)
}

func (x Country) Ptr() *Country {
	return &x
}

// MarshalText implements the text marshaller method.
func (x Country) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Country) UnmarshalText(text []byte) error {
	tmp, err := ParseCountry(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Country) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errCountryNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *Country) Scan(value interface{}) (err error) {
	if value == nil {
		*x = Country("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseCountry(v)
	case []byte:
		*x, err = ParseCountry(string(v))
	case Country:
		*x = v
	case *Country:
		if v == nil {
			return errCountryNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errCountryNilPtr
		}
		*x, err = ParseCountry(*v)
	default:
		return errors.New("invalid type for Country")
	}

	return
}

// Value implements the driver Valuer interface.
func (x Country) Value() (driver.Value, error) {
	return x.String(), nil
}
