// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package values

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// InvitationStatusPending is a InvitationStatus of type pending.
	InvitationStatusPending InvitationStatus = "pending"
	// InvitationStatusAccepted is a InvitationStatus of type accepted.
	InvitationStatusAccepted InvitationStatus = "accepted"
	// InvitationStatusExpired is a InvitationStatus of type expired.
	InvitationStatusExpired InvitationStatus = "expired"
)

var ErrInvalidInvitationStatus = fmt.Errorf("not a valid InvitationStatus, try [%s]", strings.Join(_InvitationStatusNames, ", "))

var _InvitationStatusNames = []string{
	string(InvitationStatusPending),
	string(InvitationStatusAccepted),
	string(InvitationStatusExpired),
}

// InvitationStatusNames returns a list of possible string values of InvitationStatus.
func InvitationStatusNames() []string {
	tmp := make([]string, len(_InvitationStatusNames))
	copy(tmp, _InvitationStatusNames)
	return tmp
}

// String implements the Stringer interface.
func (x InvitationStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x InvitationStatus) IsValid() bool {
	_, err := ParseInvitationStatus(string(x))
	return err == nil
}

var _InvitationStatusValue = map[string]InvitationStatus{
	"pending":  InvitationStatusPending,
	"accepted": InvitationStatusAccepted,
	"expired":  InvitationStatusExpired,
}

// ParseInvitationStatus attempts to convert a string to a InvitationStatus.
func ParseInvitationStatus(name string) (InvitationStatus, error) {
	if x, ok := _InvitationStatusValue[name]; ok {
		return x, nil
	}
	return InvitationStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidInvitationStatus)
}

func (x InvitationStatus) Ptr() *InvitationStatus {
	return &x
}

// MarshalText implements the text marshaller method.
func (x InvitationStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *InvitationStatus) UnmarshalText(text []byte) error {
	tmp, err := ParseInvitationStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *InvitationStatus) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errInvitationStatusNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *InvitationStatus) Scan(value interface{}) (err error) {
	if value == nil {
		*x = InvitationStatus("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseInvitationStatus(v)
	case []byte:
		*x, err = ParseInvitationStatus(string(v))
	case InvitationStatus:
		*x = v
	case *InvitationStatus:
		if v == nil {
			return errInvitationStatusNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errInvitationStatusNilPtr
		}
		*x, err = ParseInvitationStatus(*v)
	default:
		return errors.New("invalid type for InvitationStatus")
	}

	return
}

// Value implements the driver Valuer interface.
func (x InvitationStatus) Value() (driver.Value, error) {
	return x.String(), nil
}
