// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package values

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// MemberStatusActive is a MemberStatus of type active.
	MemberStatusActive MemberStatus = "active"
	// MemberStatusBlocked is a MemberStatus of type blocked.
	MemberStatusBlocked MemberStatus = "blocked"
)

var ErrInvalidMemberStatus = fmt.Errorf("not a valid MemberStatus, try [%s]", strings.Join(_MemberStatusNames, ", "))

var _MemberStatusNames = []string{
	string(MemberStatusActive),
	string(MemberStatusBlocked),
}

// MemberStatusNames returns a list of possible string values of MemberStatus.
func MemberStatusNames() []string {
	tmp := make([]string, len(_MemberStatusNames))
	copy(tmp, _MemberStatusNames)
	return tmp
}

// String implements the Stringer interface.
func (x MemberStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x MemberStatus) IsValid() bool {
	_, err := ParseMemberStatus(string(x))
	return err == nil
}

var _MemberStatusValue = map[string]MemberStatus{
	"active":  MemberStatusActive,
	"blocked": MemberStatusBlocked,
}

// ParseMemberStatus attempts to convert a string to a MemberStatus.
func ParseMemberStatus(name string) (MemberStatus, error) {
	if x, ok := _MemberStatusValue[name]; ok {
		return x, nil
	}
	return MemberStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidMemberStatus)
}

func (x MemberStatus) Ptr() *MemberStatus {
	return &x
}

// MarshalText implements the text marshaller method.
func (x MemberStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *MemberStatus) UnmarshalText(text []byte) error {
	tmp, err := ParseMemberStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *MemberStatus) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errMemberStatusNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *MemberStatus) Scan(value interface{}) (err error) {
	if value == nil {
		*x = MemberStatus("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseMemberStatus(v)
	case []byte:
		*x, err = ParseMemberStatus(string(v))
	case MemberStatus:
		*x = v
	case *MemberStatus:
		if v == nil {
			return errMemberStatusNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errMemberStatusNilPtr
		}
		*x, err = ParseMemberStatus(*v)
	default:
		return errors.New("invalid type for MemberStatus")
	}

	return
}

// Value implements the driver Valuer interface.
func (x MemberStatus) Value() (driver.Value, error) {
	return x.String(), nil
}
