// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package values

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// MemberRoleOwner is a MemberRole of type owner.
	MemberRoleOwner MemberRole = "owner"
	// MemberRoleAdministrator is a MemberRole of type administrator.
	MemberRoleAdministrator MemberRole = "administrator"
	// MemberRoleEmployee is a MemberRole of type employee.
	MemberRoleEmployee MemberRole = "employee"
)

var ErrInvalidMemberRole = fmt.Errorf("not a valid MemberRole, try [%s]", strings.Join(_MemberRoleNames, ", "))

var _MemberRoleNames = []string{
	string(MemberRoleOwner),
	string(MemberRoleAdministrator),
	string(MemberRoleEmployee),
}

// MemberRoleNames returns a list of possible string values of MemberRole.
func MemberRoleNames() []string {
	tmp := make([]string, len(_MemberRoleNames))
	copy(tmp, _MemberRoleNames)
	return tmp
}

// String implements the Stringer interface.
func (x MemberRole) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x MemberRole) IsValid() bool {
	_, err := ParseMemberRole(string(x))
	return err == nil
}

var _MemberRoleValue = map[string]MemberRole{
	"owner":         MemberRoleOwner,
	"administrator": MemberRoleAdministrator,
	"employee":      MemberRoleEmployee,
}

// ParseMemberRole attempts to convert a string to a MemberRole.
func ParseMemberRole(name string) (MemberRole, error) {
	if x, ok := _MemberRoleValue[name]; ok {
		return x, nil
	}
	return MemberRole(""), fmt.Errorf("%s is %w", name, ErrInvalidMemberRole)
}

func (x MemberRole) Ptr() *MemberRole {
	return &x
}

// MarshalText implements the text marshaller method.
func (x MemberRole) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *MemberRole) UnmarshalText(text []byte) error {
	tmp, err := ParseMemberRole(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *MemberRole) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errMemberRoleNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *MemberRole) Scan(value interface{}) (err error) {
	if value == nil {
		*x = MemberRole("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseMemberRole(v)
	case []byte:
		*x, err = ParseMemberRole(string(v))
	case MemberRole:
		*x = v
	case *MemberRole:
		if v == nil {
			return errMemberRoleNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errMemberRoleNilPtr
		}
		*x, err = ParseMemberRole(*v)
	default:
		return errors.New("invalid type for MemberRole")
	}

	return
}

// Value implements the driver Valuer interface.
func (x MemberRole) Value() (driver.Value, error) {
	return x.String(), nil
}
