// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package values

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// OrganizationStatusPending is a OrganizationStatus of type pending.
	OrganizationStatusPending OrganizationStatus = "pending"
	// OrganizationStatusActive is a OrganizationStatus of type active.
	OrganizationStatusActive OrganizationStatus = "active"
	// OrganizationStatusSuspended is a OrganizationStatus of type suspended.
	OrganizationStatusSuspended OrganizationStatus = "suspended"
	// OrganizationStatusRejected is a OrganizationStatus of type rejected.
	OrganizationStatusRejected OrganizationStatus = "rejected"
)

var ErrInvalidOrganizationStatus = fmt.Errorf("not a valid OrganizationStatus, try [%s]", strings.Join(_OrganizationStatusNames, ", "))

var _OrganizationStatusNames = []string{
	string(OrganizationStatusPending),
	string(OrganizationStatusActive),
	string(OrganizationStatusSuspended),
	string(OrganizationStatusRejected),
}

// OrganizationStatusNames returns a list of possible string values of OrganizationStatus.
func OrganizationStatusNames() []string {
	tmp := make([]string, len(_OrganizationStatusNames))
	copy(tmp, _OrganizationStatusNames)
	return tmp
}

// String implements the Stringer interface.
func (x OrganizationStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x OrganizationStatus) IsValid() bool {
	_, err := ParseOrganizationStatus(string(x))
	return err == nil
}

var _OrganizationStatusValue = map[string]OrganizationStatus{
	"pending":   OrganizationStatusPending,
	"active":    OrganizationStatusActive,
	"suspended": OrganizationStatusSuspended,
	"rejected":  OrganizationStatusRejected,
}

// ParseOrganizationStatus attempts to convert a string to a OrganizationStatus.
func ParseOrganizationStatus(name string) (OrganizationStatus, error) {
	if x, ok := _OrganizationStatusValue[name]; ok {
		return x, nil
	}
	return OrganizationStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidOrganizationStatus)
}

func (x OrganizationStatus) Ptr() *OrganizationStatus {
	return &x
}

// MarshalText implements the text marshaller method.
func (x OrganizationStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *OrganizationStatus) UnmarshalText(text []byte) error {
	tmp, err := ParseOrganizationStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *OrganizationStatus) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errOrganizationStatusNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *OrganizationStatus) Scan(value interface{}) (err error) {
	if value == nil {
		*x = OrganizationStatus("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseOrganizationStatus(v)
	case []byte:
		*x, err = ParseOrganizationStatus(string(v))
	case OrganizationStatus:
		*x = v
	case *OrganizationStatus:
		if v == nil {
			return errOrganizationStatusNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errOrganizationStatusNilPtr
		}
		*x, err = ParseOrganizationStatus(*v)
	default:
		return errors.New("invalid type for OrganizationStatus")
	}

	return
}

// Value implements the driver Valuer interface.
func (x OrganizationStatus) Value() (driver.Value, error) {
	return x.String(), nil
}
