// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package values

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// VehicleStatusUnconfirmed is a VehicleStatus of type unconfirmed.
	VehicleStatusUnconfirmed VehicleStatus = "unconfirmed"
	// VehicleStatusPending is a VehicleStatus of type pending.
	VehicleStatusPending VehicleStatus = "pending"
	// VehicleStatusVerified is a VehicleStatus of type verified.
	VehicleStatusVerified VehicleStatus = "verified"
	// VehicleStatusRejected is a VehicleStatus of type rejected.
	VehicleStatusRejected VehicleStatus = "rejected"
	// VehicleStatusArchived is a VehicleStatus of type archived.
	VehicleStatusArchived VehicleStatus = "archived"
)

var ErrInvalidVehicleStatus = fmt.Errorf("not a valid VehicleStatus, try [%s]", strings.Join(_VehicleStatusNames, ", "))

var _VehicleStatusNames = []string{
	string(VehicleStatusUnconfirmed),
	string(VehicleStatusPending),
	string(VehicleStatusVerified),
	string(VehicleStatusRejected),
	string(VehicleStatusArchived),
}

// VehicleStatusNames returns a list of possible string values of VehicleStatus.
func VehicleStatusNames() []string {
	tmp := make([]string, len(_VehicleStatusNames))
	copy(tmp, _VehicleStatusNames)
	return tmp
}

// String implements the Stringer interface.
func (x VehicleStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x VehicleStatus) IsValid() bool {
	_, err := ParseVehicleStatus(string(x))
	return err == nil
}

var _VehicleStatusValue = map[string]VehicleStatus{
	"unconfirmed": VehicleStatusUnconfirmed,
	"pending":     VehicleStatusPending,
	"verified":    VehicleStatusVerified,
	"rejected":    VehicleStatusRejected,
	"archived":    VehicleStatusArchived,
}

// ParseVehicleStatus attempts to convert a string to a VehicleStatus.
func ParseVehicleStatus(name string) (VehicleStatus, error) {
	if x, ok := _VehicleStatusValue[name]; ok {
		return x, nil
	}
	return VehicleStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidVehicleStatus)
}

func (x VehicleStatus) Ptr() *VehicleStatus {
	return &x
}

// MarshalText implements the text marshaller method.
func (x VehicleStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *VehicleStatus) UnmarshalText(text []byte) error {
	tmp, err := ParseVehicleStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *VehicleStatus) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errVehicleStatusNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *VehicleStatus) Scan(value interface{}) (err error) {
	if value == nil {
		*x = VehicleStatus("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseVehicleStatus(v)
	case []byte:
		*x, err = ParseVehicleStatus(string(v))
	case VehicleStatus:
		*x = v
	case *VehicleStatus:
		if v == nil {
			return errVehicleStatusNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errVehicleStatusNilPtr
		}
		*x, err = ParseVehicleStatus(*v)
	default:
		return errors.New("invalid type for VehicleStatus")
	}

	return
}

// Value implements the driver Valuer interface.
func (x VehicleStatus) Value() (driver.Value, error) {
	return x.String(), nil
}
