// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package values

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// TicketStatusOpen is a TicketStatus of type open.
	TicketStatusOpen TicketStatus = "open"
	// TicketStatusAnswered is a TicketStatus of type answered.
	TicketStatusAnswered TicketStatus = "answered"
	// TicketStatusAwaitingReply is a TicketStatus of type awaiting_reply.
	TicketStatusAwaitingReply TicketStatus = "awaiting_reply"
	// TicketStatusClosed is a TicketStatus of type closed.
	TicketStatusClosed TicketStatus = "closed"
)

var ErrInvalidTicketStatus = fmt.Errorf("not a valid TicketStatus, try [%s]", strings.Join(_TicketStatusNames, ", "))

var _TicketStatusNames = []string{
	string(TicketStatusOpen),
	string(TicketStatusAnswered),
	string(TicketStatusAwaitingReply),
	string(TicketStatusClosed),
}

// TicketStatusNames returns a list of possible string values of TicketStatus.
func TicketStatusNames() []string {
	tmp := make([]string, len(_TicketStatusNames))
	copy(tmp, _TicketStatusNames)
	return tmp
}

// String implements the Stringer interface.
func (x TicketStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x TicketStatus) IsValid() bool {
	_, err := ParseTicketStatus(string(x))
	return err == nil
}

var _TicketStatusValue = map[string]TicketStatus{
	"open":           TicketStatusOpen,
	"answered":       TicketStatusAnswered,
	"awaiting_reply": TicketStatusAwaitingReply,
	"closed":         TicketStatusClosed,
}

// ParseTicketStatus attempts to convert a string to a TicketStatus.
func ParseTicketStatus(name string) (TicketStatus, error) {
	if x, ok := _TicketStatusValue[name]; ok {
		return x, nil
	}
	return TicketStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidTicketStatus)
}

func (x TicketStatus) Ptr() *TicketStatus {
	return &x
}

// MarshalText implements the text marshaller method.
func (x TicketStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *TicketStatus) UnmarshalText(text []byte) error {
	tmp, err := ParseTicketStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *TicketStatus) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errTicketStatusNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *TicketStatus) Scan(value interface{}) (err error) {
	if value == nil {
		*x = TicketStatus("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseTicketStatus(v)
	case []byte:
		*x, err = ParseTicketStatus(string(v))
	case TicketStatus:
		*x = v
	case *TicketStatus:
		if v == nil {
			return errTicketStatusNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errTicketStatusNilPtr
		}
		*x, err = ParseTicketStatus(*v)
	default:
		return errors.New("invalid type for TicketStatus")
	}

	return
}

// Value implements the driver Valuer interface.
func (x TicketStatus) Value() (driver.Value, error) {
	return x.String(), nil
}
