// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package values

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// OrderStatusActive is a OrderStatus of type active.
	OrderStatusActive OrderStatus = "active"
	// OrderStatusCustomerCompleted is a OrderStatus of type customer_completed.
	OrderStatusCustomerCompleted OrderStatus = "customer_completed"
	// OrderStatusCarrierCompleted is a OrderStatus of type carrier_completed.
	OrderStatusCarrierCompleted OrderStatus = "carrier_completed"
	// OrderStatusCompleted is a OrderStatus of type completed.
	OrderStatusCompleted OrderStatus = "completed"
	// OrderStatusCancelledByCustomer is a OrderStatus of type cancelled_by_customer.
	OrderStatusCancelledByCustomer OrderStatus = "cancelled_by_customer"
	// OrderStatusCancelledByCarrier is a OrderStatus of type cancelled_by_carrier.
	OrderStatusCancelledByCarrier OrderStatus = "cancelled_by_carrier"
)

var ErrInvalidOrderStatus = fmt.Errorf("not a valid OrderStatus, try [%s]", strings.Join(_OrderStatusNames, ", "))

var _OrderStatusNames = []string{
	string(OrderStatusActive),
	string(OrderStatusCustomerCompleted),
	string(OrderStatusCarrierCompleted),
	string(OrderStatusCompleted),
	string(OrderStatusCancelledByCustomer),
	string(OrderStatusCancelledByCarrier),
}

// OrderStatusNames returns a list of possible string values of OrderStatus.
func OrderStatusNames() []string {
	tmp := make([]string, len(_OrderStatusNames))
	copy(tmp, _OrderStatusNames)
	return tmp
}

// String implements the Stringer interface.
func (x OrderStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x OrderStatus) IsValid() bool {
	_, err := ParseOrderStatus(string(x))
	return err == nil
}

var _OrderStatusValue = map[string]OrderStatus{
	"active":                OrderStatusActive,
	"customer_completed":    OrderStatusCustomerCompleted,
	"carrier_completed":     OrderStatusCarrierCompleted,
	"completed":             OrderStatusCompleted,
	"cancelled_by_customer": OrderStatusCancelledByCustomer,
	"cancelled_by_carrier":  OrderStatusCancelledByCarrier,
}

// ParseOrderStatus attempts to convert a string to a OrderStatus.
func ParseOrderStatus(name string) (OrderStatus, error) {
	if x, ok := _OrderStatusValue[name]; ok {
		return x, nil
	}
	return OrderStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidOrderStatus)
}

func (x OrderStatus) Ptr() *OrderStatus {
	return &x
}

// MarshalText implements the text marshaller method.
func (x OrderStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *OrderStatus) UnmarshalText(text []byte) error {
	tmp, err := ParseOrderStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *OrderStatus) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errOrderStatusNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *OrderStatus) Scan(value interface{}) (err error) {
	if value == nil {
		*x = OrderStatus("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseOrderStatus(v)
	case []byte:
		*x, err = ParseOrderStatus(string(v))
	case OrderStatus:
		*x = v
	case *OrderStatus:
		if v == nil {
			return errOrderStatusNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errOrderStatusNilPtr
		}
		*x, err = ParseOrderStatus(*v)
	default:
		return errors.New("invalid type for OrderStatus")
	}

	return
}

// Value implements the driver Valuer interface.
func (x OrderStatus) Value() (driver.Value, error) {
	return x.String(), nil
}
