// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package values

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// ADRClassNone is a ADRClass of type none.
	ADRClassNone ADRClass = "none"
	// ADRClassClass1 is a ADRClass of type class1.
	ADRClassClass1 ADRClass = "class1"
	// ADRClassClass2 is a ADRClass of type class2.
	ADRClassClass2 ADRClass = "class2"
	// ADRClassClass3 is a ADRClass of type class3.
	ADRClassClass3 ADRClass = "class3"
	// ADRClassClass4 is a ADRClass of type class4.
	ADRClassClass4 ADRClass = "class4"
	// ADRClassClass5 is a ADRClass of type class5.
	ADRClassClass5 ADRClass = "class5"
	// ADRClassClass6 is a ADRClass of type class6.
	ADRClassClass6 ADRClass = "class6"
	// ADRClassClass7 is a ADRClass of type class7.
	ADRClassClass7 ADRClass = "class7"
	// ADRClassClass8 is a ADRClass of type class8.
	ADRClassClass8 ADRClass = "class8"
	// ADRClassClass9 is a ADRClass of type class9.
	ADRClassClass9 ADRClass = "class9"
)

var ErrInvalidADRClass = fmt.Errorf("not a valid ADRClass, try [%s]", strings.Join(_ADRClassNames, ", "))

var _ADRClassNames = []string{
	string(ADRClassNone),
	string(ADRClassClass1),
	string(ADRClassClass2),
	string(ADRClassClass3),
	string(ADRClassClass4),
	string(ADRClassClass5),
	string(ADRClassClass6),
	string(ADRClassClass7),
	string(ADRClassClass8),
	string(ADRClassClass9),
}

// ADRClassNames returns a list of possible string values of ADRClass.
func ADRClassNames() []string {
	tmp := make([]string, len(_ADRClassNames))
	copy(tmp, _ADRClassNames)
	return tmp
}

// String implements the Stringer interface.
func (x ADRClass) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ADRClass) IsValid() bool {
	_, err := ParseADRClass(string(x))
	return err == nil
}

var _ADRClassValue = map[string]ADRClass{
	"none":   ADRClassNone,
	"class1": ADRClassClass1,
	"class2": ADRClassClass2,
	"class3": ADRClassClass3,
	"class4": ADRClassClass4,
	"class5": ADRClassClass5,
	"class6": ADRClassClass6,
	"class7": ADRClassClass7,
	"class8": ADRClassClass8,
	"class9": ADRClassClass9,
}

// ParseADRClass attempts to convert a string to a ADRClass.
func ParseADRClass(name string) (ADRClass, error) {
	if x, ok := _ADRClassValue[name]; ok {
		return x, nil
	}
	return ADRClass(""), fmt.Errorf("%s is %w", name, ErrInvalidADRClass)
}

func (x ADRClass) Ptr() *ADRClass {
	return &x
}

// MarshalText implements the text marshaller method.
func (x ADRClass) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ADRClass) UnmarshalText(text []byte) error {
	tmp, err := ParseADRClass(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ADRClass) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errADRClassNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *ADRClass) Scan(value interface{}) (err error) {
	if value == nil {
		*x = ADRClass("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseADRClass(v)
	case []byte:
		*x, err = ParseADRClass(string(v))
	case ADRClass:
		*x = v
	case *ADRClass:
		if v == nil {
			return errADRClassNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errADRClassNilPtr
		}
		*x, err = ParseADRClass(*v)
	default:
		return errors.New("invalid type for ADRClass")
	}

	return
}

// Value implements the driver Valuer interface.
func (x ADRClass) Value() (driver.Value, error) {
	return x.String(), nil
}
