// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package values

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// BodyTypeTent is a BodyType of type tent.
	BodyTypeTent BodyType = "tent"
	// BodyTypeRefrigerator is a BodyType of type refrigerator.
	BodyTypeRefrigerator BodyType = "refrigerator"
	// BodyTypeIsothermal is a BodyType of type isothermal.
	BodyTypeIsothermal BodyType = "isothermal"
	// BodyTypeContainer is a BodyType of type container.
	BodyTypeContainer BodyType = "container"
	// BodyTypeOpenbed is a BodyType of type openbed.
	BodyTypeOpenbed BodyType = "openbed"
	// BodyTypeLowbed is a BodyType of type lowbed.
	BodyTypeLowbed BodyType = "lowbed"
	// BodyTypeJumbo is a BodyType of type jumbo.
	BodyTypeJumbo BodyType = "jumbo"
	// BodyTypeTank is a BodyType of type tank.
	BodyTypeTank BodyType = "tank"
	// BodyTypeTipper is a BodyType of type tipper.
	BodyTypeTipper BodyType = "tipper"
)

var ErrInvalidBodyType = fmt.Errorf("not a valid BodyType, try [%s]", strings.Join(_BodyTypeNames, ", "))

var _BodyTypeNames = []string{
	string(BodyTypeTent),
	string(BodyTypeRefrigerator),
	string(BodyTypeIsothermal),
	string(BodyTypeContainer),
	string(BodyTypeOpenbed),
	string(BodyTypeLowbed),
	string(BodyTypeJumbo),
	string(BodyTypeTank),
	string(BodyTypeTipper),
}

// BodyTypeNames returns a list of possible string values of BodyType.
func BodyTypeNames() []string {
	tmp := make([]string, len(_BodyTypeNames))
	copy(tmp, _BodyTypeNames)
	return tmp
}

// String implements the Stringer interface.
func (x BodyType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x BodyType) IsValid() bool {
	_, err := ParseBodyType(string(x))
	return err == nil
}

var _BodyTypeValue = map[string]BodyType{
	"tent":         BodyTypeTent,
	"refrigerator": BodyTypeRefrigerator,
	"isothermal":   BodyTypeIsothermal,
	"container":    BodyTypeContainer,
	"openbed":      BodyTypeOpenbed,
	"lowbed":       BodyTypeLowbed,
	"jumbo":        BodyTypeJumbo,
	"tank":         BodyTypeTank,
	"tipper":       BodyTypeTipper,
}

// ParseBodyType attempts to convert a string to a BodyType.
func ParseBodyType(name string) (BodyType, error) {
	if x, ok := _BodyTypeValue[name]; ok {
		return x, nil
	}
	return BodyType(""), fmt.Errorf("%s is %w", name, ErrInvalidBodyType)
}

func (x BodyType) Ptr() *BodyType {
	return &x
}

// MarshalText implements the text marshaller method.
func (x BodyType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *BodyType) UnmarshalText(text []byte) error {
	tmp, err := ParseBodyType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *BodyType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errBodyTypeNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *BodyType) Scan(value interface{}) (err error) {
	if value == nil {
		*x = BodyType("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseBodyType(v)
	case []byte:
		*x, err = ParseBodyType(string(v))
	case BodyType:
		*x = v
	case *BodyType:
		if v == nil {
			return errBodyTypeNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errBodyTypeNilPtr
		}
		*x, err = ParseBodyType(*v)
	default:
		return errors.New("invalid type for BodyType")
	}

	return
}

// Value implements the driver Valuer interface.
func (x BodyType) Value() (driver.Value, error) {
	return x.String(), nil
}
