// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package values

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// CargoTypeGeneral is a CargoType of type general.
	CargoTypeGeneral CargoType = "general"
	// CargoTypeBulk is a CargoType of type bulk.
	CargoTypeBulk CargoType = "bulk"
	// CargoTypeLiquid is a CargoType of type liquid.
	CargoTypeLiquid CargoType = "liquid"
	// CargoTypeRefrigerated is a CargoType of type refrigerated.
	CargoTypeRefrigerated CargoType = "refrigerated"
	// CargoTypeDangerous is a CargoType of type dangerous.
	CargoTypeDangerous CargoType = "dangerous"
	// CargoTypeOversized is a CargoType of type oversized.
	CargoTypeOversized CargoType = "oversized"
	// CargoTypeContainer is a CargoType of type container.
	CargoTypeContainer CargoType = "container"
)

var ErrInvalidCargoType = fmt.Errorf("not a valid CargoType, try [%s]", strings.Join(_CargoTypeNames, ", "))

var _CargoTypeNames = []string{
	string(CargoTypeGeneral),
	string(CargoTypeBulk),
	string(CargoTypeLiquid),
	string(CargoTypeRefrigerated),
	string(CargoTypeDangerous),
	string(CargoTypeOversized),
	string(CargoTypeContainer),
}

// CargoTypeNames returns a list of possible string values of CargoType.
func CargoTypeNames() []string {
	tmp := make([]string, len(_CargoTypeNames))
	copy(tmp, _CargoTypeNames)
	return tmp
}

// String implements the Stringer interface.
func (x CargoType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x CargoType) IsValid() bool {
	_, err := ParseCargoType(string(x))
	return err == nil
}

var _CargoTypeValue = map[string]CargoType{
	"general":      CargoTypeGeneral,
	"bulk":         CargoTypeBulk,
	"liquid":       CargoTypeLiquid,
	"refrigerated": CargoTypeRefrigerated,
	"dangerous":    CargoTypeDangerous,
	"oversized":    CargoTypeOversized,
	"container":    CargoTypeContainer,
}

// ParseCargoType attempts to convert a string to a CargoType.
func ParseCargoType(name string) (CargoType, error) {
	if x, ok := _CargoTypeValue[name]; ok {
		return x, nil
	}
	return CargoType(""), fmt.Errorf("%s is %w", name, ErrInvalidCargoType)
}

func (x CargoType) Ptr() *CargoType {
	return &x
}

// MarshalText implements the text marshaller method.
func (x CargoType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *CargoType) UnmarshalText(text []byte) error {
	tmp, err := ParseCargoType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *CargoType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errCargoTypeNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *CargoType) Scan(value interface{}) (err error) {
	if value == nil {
		*x = CargoType("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseCargoType(v)
	case []byte:
		*x, err = ParseCargoType(string(v))
	case CargoType:
		*x = v
	case *CargoType:
		if v == nil {
			return errCargoTypeNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errCargoTypeNilPtr
		}
		*x, err = ParseCargoType(*v)
	default:
		return errors.New("invalid type for CargoType")
	}

	return
}

// Value implements the driver Valuer interface.
func (x CargoType) Value() (driver.Value, error) {
	return x.String(), nil
}
