// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package values

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// CurrencyRUB is a Currency of type RUB.
	CurrencyRUB Currency = "RUB"
	// CurrencyKZT is a Currency of type KZT.
	CurrencyKZT Currency = "KZT"
	// CurrencyBYN is a Currency of type BYN.
	CurrencyBYN Currency = "BYN"
	// CurrencyEUR is a Currency of type EUR.
	CurrencyEUR Currency = "EUR"
	// CurrencyUSD is a Currency of type USD.
	CurrencyUSD Currency = "USD"
)

var ErrInvalidCurrency = fmt.Errorf("not a valid Currency, try [%s]", strings.Join(_CurrencyNames, ", "))

var _CurrencyNames = []string{
	string(CurrencyRUB),
	string(CurrencyKZT),
	string(CurrencyBYN),
	string(CurrencyEUR),
	string(CurrencyUSD),
}

// CurrencyNames returns a list of possible string values of Currency.
func CurrencyNames() []string {
	tmp := make([]string, len(_CurrencyNames))
	copy(tmp, _CurrencyNames)
	return tmp
}

// String implements the Stringer interface.
func (x Currency) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Currency) IsValid() bool {
	_, err := ParseCurrency(string(x))
	return err == nil
}

var _CurrencyValue = map[string]Currency{
	"RUB": CurrencyRUB,
	"KZT": CurrencyKZT,
	"BYN": CurrencyBYN,
	"EUR": CurrencyEUR,
	"USD": CurrencyUSD,
}

// ParseCurrency attempts to convert a string to a Currency.
func ParseCurrency(name string) (Currency, error) {
	if x, ok := _CurrencyValue[name]; ok {
		return x, nil
	}
	return Currency(""), fmt.Errorf("%s is %w", name, ErrInvalidCurrency)
}

func (x Currency) Ptr() *Currency {
	return &x
}

// MarshalText implements the text marshaller method.
func (x Currency) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Currency) UnmarshalText(text []byte) error {
	tmp, err := ParseCurrency(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Currency) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errCurrencyNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *Currency) Scan(value interface{}) (err error) {
	if value == nil {
		*x = Currency("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseCurrency(v)
	case []byte:
		*x, err = ParseCurrency(string(v))
	case Currency:
		*x = v
	case *Currency:
		if v == nil {
			return errCurrencyNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errCurrencyNilPtr
		}
		*x, err = ParseCurrency(*v)
	default:
		return errors.New("invalid type for Currency")
	}

	return
}

// Value implements the driver Valuer interface.
func (x Currency) Value() (driver.Value, error) {
	return x.String(), nil
}
