// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package values

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// LoadingTypeRear is a LoadingType of type rear.
	LoadingTypeRear LoadingType = "rear"
	// LoadingTypeSide is a LoadingType of type side.
	LoadingTypeSide LoadingType = "side"
	// LoadingTypeTop is a LoadingType of type top.
	LoadingTypeTop LoadingType = "top"
	// LoadingTypeFullUntarp is a LoadingType of type full_untarp.
	LoadingTypeFullUntarp LoadingType = "full_untarp"
)

var ErrInvalidLoadingType = fmt.Errorf("not a valid LoadingType, try [%s]", strings.Join(_LoadingTypeNames, ", "))

var _LoadingTypeNames = []string{
	string(LoadingTypeRear),
	string(LoadingTypeSide),
	string(LoadingTypeTop),
	string(LoadingTypeFullUntarp),
}

// LoadingTypeNames returns a list of possible string values of LoadingType.
func LoadingTypeNames() []string {
	tmp := make([]string, len(_LoadingTypeNames))
	copy(tmp, _LoadingTypeNames)
	return tmp
}

// String implements the Stringer interface.
func (x LoadingType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x LoadingType) IsValid() bool {
	_, err := ParseLoadingType(string(x))
	return err == nil
}

var _LoadingTypeValue = map[string]LoadingType{
	"rear":        LoadingTypeRear,
	"side":        LoadingTypeSide,
	"top":         LoadingTypeTop,
	"full_untarp": LoadingTypeFullUntarp,
}

// ParseLoadingType attempts to convert a string to a LoadingType.
func ParseLoadingType(name string) (LoadingType, error) {
	if x, ok := _LoadingTypeValue[name]; ok {
		return x, nil
	}
	return LoadingType(""), fmt.Errorf("%s is %w", name, ErrInvalidLoadingType)
}

func (x LoadingType) Ptr() *LoadingType {
	return &x
}

// MarshalText implements the text marshaller method.
func (x LoadingType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *LoadingType) UnmarshalText(text []byte) error {
	tmp, err := ParseLoadingType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *LoadingType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errLoadingTypeNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *LoadingType) Scan(value interface{}) (err error) {
	if value == nil {
		*x = LoadingType("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseLoadingType(v)
	case []byte:
		*x, err = ParseLoadingType(string(v))
	case LoadingType:
		*x = v
	case *LoadingType:
		if v == nil {
			return errLoadingTypeNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errLoadingTypeNilPtr
		}
		*x, err = ParseLoadingType(*v)
	default:
		return errors.New("invalid type for LoadingType")
	}

	return
}

// Value implements the driver Valuer interface.
func (x LoadingType) Value() (driver.Value, error) {
	return x.String(), nil
}
