// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package values

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// OfferStatusPending is a OfferStatus of type pending.
	OfferStatusPending OfferStatus = "pending"
	// OfferStatusSelected is a OfferStatus of type selected.
	OfferStatusSelected OfferStatus = "selected"
	// OfferStatusConfirmed is a OfferStatus of type confirmed.
	OfferStatusConfirmed OfferStatus = "confirmed"
	// OfferStatusRejected is a OfferStatus of type rejected.
	OfferStatusRejected OfferStatus = "rejected"
	// OfferStatusWithdrawn is a OfferStatus of type withdrawn.
	OfferStatusWithdrawn OfferStatus = "withdrawn"
	// OfferStatusDeclined is a OfferStatus of type declined.
	OfferStatusDeclined OfferStatus = "declined"
)

var ErrInvalidOfferStatus = fmt.Errorf("not a valid OfferStatus, try [%s]", strings.Join(_OfferStatusNames, ", "))

var _OfferStatusNames = []string{
	string(OfferStatusPending),
	string(OfferStatusSelected),
	string(OfferStatusConfirmed),
	string(OfferStatusRejected),
	string(OfferStatusWithdrawn),
	string(OfferStatusDeclined),
}

// OfferStatusNames returns a list of possible string values of OfferStatus.
func OfferStatusNames() []string {
	tmp := make([]string, len(_OfferStatusNames))
	copy(tmp, _OfferStatusNames)
	return tmp
}

// String implements the Stringer interface.
func (x OfferStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x OfferStatus) IsValid() bool {
	_, err := ParseOfferStatus(string(x))
	return err == nil
}

var _OfferStatusValue = map[string]OfferStatus{
	"pending":   OfferStatusPending,
	"selected":  OfferStatusSelected,
	"confirmed": OfferStatusConfirmed,
	"rejected":  OfferStatusRejected,
	"withdrawn": OfferStatusWithdrawn,
	"declined":  OfferStatusDeclined,
}

// ParseOfferStatus attempts to convert a string to a OfferStatus.
func ParseOfferStatus(name string) (OfferStatus, error) {
	if x, ok := _OfferStatusValue[name]; ok {
		return x, nil
	}
	return OfferStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidOfferStatus)
}

func (x OfferStatus) Ptr() *OfferStatus {
	return &x
}

// MarshalText implements the text marshaller method.
func (x OfferStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *OfferStatus) UnmarshalText(text []byte) error {
	tmp, err := ParseOfferStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *OfferStatus) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errOfferStatusNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *OfferStatus) Scan(value interface{}) (err error) {
	if value == nil {
		*x = OfferStatus("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseOfferStatus(v)
	case []byte:
		*x, err = ParseOfferStatus(string(v))
	case OfferStatus:
		*x = v
	case *OfferStatus:
		if v == nil {
			return errOfferStatusNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errOfferStatusNilPtr
		}
		*x, err = ParseOfferStatus(*v)
	default:
		return errors.New("invalid type for OfferStatus")
	}

	return
}

// Value implements the driver Valuer interface.
func (x OfferStatus) Value() (driver.Value, error) {
	return x.String(), nil
}
