// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package values

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// PaymentTermsPrepaid is a PaymentTerms of type prepaid.
	PaymentTermsPrepaid PaymentTerms = "prepaid"
	// PaymentTermsOnLoading is a PaymentTerms of type on_loading.
	PaymentTermsOnLoading PaymentTerms = "on_loading"
	// PaymentTermsOnUnloading is a PaymentTerms of type on_unloading.
	PaymentTermsOnUnloading PaymentTerms = "on_unloading"
	// PaymentTermsDeferred is a PaymentTerms of type deferred.
	PaymentTermsDeferred PaymentTerms = "deferred"
)

var ErrInvalidPaymentTerms = fmt.Errorf("not a valid PaymentTerms, try [%s]", strings.Join(_PaymentTermsNames, ", "))

var _PaymentTermsNames = []string{
	string(PaymentTermsPrepaid),
	string(PaymentTermsOnLoading),
	string(PaymentTermsOnUnloading),
	string(PaymentTermsDeferred),
}

// PaymentTermsNames returns a list of possible string values of PaymentTerms.
func PaymentTermsNames() []string {
	tmp := make([]string, len(_PaymentTermsNames))
	copy(tmp, _PaymentTermsNames)
	return tmp
}

// String implements the Stringer interface.
func (x PaymentTerms) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x PaymentTerms) IsValid() bool {
	_, err := ParsePaymentTerms(string(x))
	return err == nil
}

var _PaymentTermsValue = map[string]PaymentTerms{
	"prepaid":      PaymentTermsPrepaid,
	"on_loading":   PaymentTermsOnLoading,
	"on_unloading": PaymentTermsOnUnloading,
	"deferred":     PaymentTermsDeferred,
}

// ParsePaymentTerms attempts to convert a string to a PaymentTerms.
func ParsePaymentTerms(name string) (PaymentTerms, error) {
	if x, ok := _PaymentTermsValue[name]; ok {
		return x, nil
	}
	return PaymentTerms(""), fmt.Errorf("%s is %w", name, ErrInvalidPaymentTerms)
}

func (x PaymentTerms) Ptr() *PaymentTerms {
	return &x
}

// MarshalText implements the text marshaller method.
func (x PaymentTerms) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *PaymentTerms) UnmarshalText(text []byte) error {
	tmp, err := ParsePaymentTerms(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *PaymentTerms) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errPaymentTermsNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *PaymentTerms) Scan(value interface{}) (err error) {
	if value == nil {
		*x = PaymentTerms("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParsePaymentTerms(v)
	case []byte:
		*x, err = ParsePaymentTerms(string(v))
	case PaymentTerms:
		*x = v
	case *PaymentTerms:
		if v == nil {
			return errPaymentTermsNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errPaymentTermsNilPtr
		}
		*x, err = ParsePaymentTerms(*v)
	default:
		return errors.New("invalid type for PaymentTerms")
	}

	return
}

// Value implements the driver Valuer interface.
func (x PaymentTerms) Value() (driver.Value, error) {
	return x.String(), nil
}
