// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package values

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// PaymentMethodBankTransfer is a PaymentMethod of type bank_transfer.
	PaymentMethodBankTransfer PaymentMethod = "bank_transfer"
	// PaymentMethodCash is a PaymentMethod of type cash.
	PaymentMethodCash PaymentMethod = "cash"
	// PaymentMethodCard is a PaymentMethod of type card.
	PaymentMethodCard PaymentMethod = "card"
)

var ErrInvalidPaymentMethod = fmt.Errorf("not a valid PaymentMethod, try [%s]", strings.Join(_PaymentMethodNames, ", "))

var _PaymentMethodNames = []string{
	string(PaymentMethodBankTransfer),
	string(PaymentMethodCash),
	string(PaymentMethodCard),
}

// PaymentMethodNames returns a list of possible string values of PaymentMethod.
func PaymentMethodNames() []string {
	tmp := make([]string, len(_PaymentMethodNames))
	copy(tmp, _PaymentMethodNames)
	return tmp
}

// String implements the Stringer interface.
func (x PaymentMethod) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x PaymentMethod) IsValid() bool {
	_, err := ParsePaymentMethod(string(x))
	return err == nil
}

var _PaymentMethodValue = map[string]PaymentMethod{
	"bank_transfer": PaymentMethodBankTransfer,
	"cash":          PaymentMethodCash,
	"card":          PaymentMethodCard,
}

// ParsePaymentMethod attempts to convert a string to a PaymentMethod.
func ParsePaymentMethod(name string) (PaymentMethod, error) {
	if x, ok := _PaymentMethodValue[name]; ok {
		return x, nil
	}
	return PaymentMethod(""), fmt.Errorf("%s is %w", name, ErrInvalidPaymentMethod)
}

func (x PaymentMethod) Ptr() *PaymentMethod {
	return &x
}

// MarshalText implements the text marshaller method.
func (x PaymentMethod) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *PaymentMethod) UnmarshalText(text []byte) error {
	tmp, err := ParsePaymentMethod(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *PaymentMethod) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errPaymentMethodNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *PaymentMethod) Scan(value interface{}) (err error) {
	if value == nil {
		*x = PaymentMethod("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParsePaymentMethod(v)
	case []byte:
		*x, err = ParsePaymentMethod(string(v))
	case PaymentMethod:
		*x = v
	case *PaymentMethod:
		if v == nil {
			return errPaymentMethodNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errPaymentMethodNilPtr
		}
		*x, err = ParsePaymentMethod(*v)
	default:
		return errors.New("invalid type for PaymentMethod")
	}

	return
}

// Value implements the driver Valuer interface.
func (x PaymentMethod) Value() (driver.Value, error) {
	return x.String(), nil
}
