// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package values

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// FreightRequestStatusPublished is a FreightRequestStatus of type published.
	FreightRequestStatusPublished FreightRequestStatus = "published"
	// FreightRequestStatusSelected is a FreightRequestStatus of type selected.
	FreightRequestStatusSelected FreightRequestStatus = "selected"
	// FreightRequestStatusConfirmed is a FreightRequestStatus of type confirmed.
	FreightRequestStatusConfirmed FreightRequestStatus = "confirmed"
	// FreightRequestStatusCancelled is a FreightRequestStatus of type cancelled.
	FreightRequestStatusCancelled FreightRequestStatus = "cancelled"
	// FreightRequestStatusExpired is a FreightRequestStatus of type expired.
	FreightRequestStatusExpired FreightRequestStatus = "expired"
)

var ErrInvalidFreightRequestStatus = fmt.Errorf("not a valid FreightRequestStatus, try [%s]", strings.Join(_FreightRequestStatusNames, ", "))

var _FreightRequestStatusNames = []string{
	string(FreightRequestStatusPublished),
	string(FreightRequestStatusSelected),
	string(FreightRequestStatusConfirmed),
	string(FreightRequestStatusCancelled),
	string(FreightRequestStatusExpired),
}

// FreightRequestStatusNames returns a list of possible string values of FreightRequestStatus.
func FreightRequestStatusNames() []string {
	tmp := make([]string, len(_FreightRequestStatusNames))
	copy(tmp, _FreightRequestStatusNames)
	return tmp
}

// String implements the Stringer interface.
func (x FreightRequestStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x FreightRequestStatus) IsValid() bool {
	_, err := ParseFreightRequestStatus(string(x))
	return err == nil
}

var _FreightRequestStatusValue = map[string]FreightRequestStatus{
	"published": FreightRequestStatusPublished,
	"selected":  FreightRequestStatusSelected,
	"confirmed": FreightRequestStatusConfirmed,
	"cancelled": FreightRequestStatusCancelled,
	"expired":   FreightRequestStatusExpired,
}

// ParseFreightRequestStatus attempts to convert a string to a FreightRequestStatus.
func ParseFreightRequestStatus(name string) (FreightRequestStatus, error) {
	if x, ok := _FreightRequestStatusValue[name]; ok {
		return x, nil
	}
	return FreightRequestStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidFreightRequestStatus)
}

func (x FreightRequestStatus) Ptr() *FreightRequestStatus {
	return &x
}

// MarshalText implements the text marshaller method.
func (x FreightRequestStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *FreightRequestStatus) UnmarshalText(text []byte) error {
	tmp, err := ParseFreightRequestStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *FreightRequestStatus) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errFreightRequestStatusNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *FreightRequestStatus) Scan(value interface{}) (err error) {
	if value == nil {
		*x = FreightRequestStatus("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseFreightRequestStatus(v)
	case []byte:
		*x, err = ParseFreightRequestStatus(string(v))
	case FreightRequestStatus:
		*x = v
	case *FreightRequestStatus:
		if v == nil {
			return errFreightRequestStatusNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errFreightRequestStatusNilPtr
		}
		*x, err = ParseFreightRequestStatus(*v)
	default:
		return errors.New("invalid type for FreightRequestStatus")
	}

	return
}

// Value implements the driver Valuer interface.
func (x FreightRequestStatus) Value() (driver.Value, error) {
	return x.String(), nil
}
