// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package values

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// VatTypeIncluded is a VatType of type included.
	VatTypeIncluded VatType = "included"
	// VatTypeExcluded is a VatType of type excluded.
	VatTypeExcluded VatType = "excluded"
	// VatTypeNone is a VatType of type none.
	VatTypeNone VatType = "none"
)

var ErrInvalidVatType = fmt.Errorf("not a valid VatType, try [%s]", strings.Join(_VatTypeNames, ", "))

var _VatTypeNames = []string{
	string(VatTypeIncluded),
	string(VatTypeExcluded),
	string(VatTypeNone),
}

// VatTypeNames returns a list of possible string values of VatType.
func VatTypeNames() []string {
	tmp := make([]string, len(_VatTypeNames))
	copy(tmp, _VatTypeNames)
	return tmp
}

// String implements the Stringer interface.
func (x VatType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x VatType) IsValid() bool {
	_, err := ParseVatType(string(x))
	return err == nil
}

var _VatTypeValue = map[string]VatType{
	"included": VatTypeIncluded,
	"excluded": VatTypeExcluded,
	"none":     VatTypeNone,
}

// ParseVatType attempts to convert a string to a VatType.
func ParseVatType(name string) (VatType, error) {
	if x, ok := _VatTypeValue[name]; ok {
		return x, nil
	}
	return VatType(""), fmt.Errorf("%s is %w", name, ErrInvalidVatType)
}

func (x VatType) Ptr() *VatType {
	return &x
}

// MarshalText implements the text marshaller method.
func (x VatType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *VatType) UnmarshalText(text []byte) error {
	tmp, err := ParseVatType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *VatType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errVatTypeNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *VatType) Scan(value interface{}) (err error) {
	if value == nil {
		*x = VatType("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseVatType(v)
	case []byte:
		*x, err = ParseVatType(string(v))
	case VatType:
		*x = v
	case *VatType:
		if v == nil {
			return errVatTypeNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errVatTypeNilPtr
		}
		*x, err = ParseVatType(*v)
	default:
		return errors.New("invalid type for VatType")
	}

	return
}

// Value implements the driver Valuer interface.
func (x VatType) Value() (driver.Value, error) {
	return x.String(), nil
}
