// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package values

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// VehicleTypeVan is a VehicleType of type van.
	VehicleTypeVan VehicleType = "van"
	// VehicleTypeFlatbed is a VehicleType of type flatbed.
	VehicleTypeFlatbed VehicleType = "flatbed"
	// VehicleTypeTanker is a VehicleType of type tanker.
	VehicleTypeTanker VehicleType = "tanker"
	// VehicleTypeDumpTruck is a VehicleType of type dump_truck.
	VehicleTypeDumpTruck VehicleType = "dump_truck"
	// VehicleTypeSpecializedTruck is a VehicleType of type specialized_truck.
	VehicleTypeSpecializedTruck VehicleType = "specialized_truck"
	// VehicleTypeLightTruck is a VehicleType of type light_truck.
	VehicleTypeLightTruck VehicleType = "light_truck"
	// VehicleTypeMediumTruck is a VehicleType of type medium_truck.
	VehicleTypeMediumTruck VehicleType = "medium_truck"
	// VehicleTypeHeavyTruck is a VehicleType of type heavy_truck.
	VehicleTypeHeavyTruck VehicleType = "heavy_truck"
)

var ErrInvalidVehicleType = fmt.Errorf("not a valid VehicleType, try [%s]", strings.Join(_VehicleTypeNames, ", "))

var _VehicleTypeNames = []string{
	string(VehicleTypeVan),
	string(VehicleTypeFlatbed),
	string(VehicleTypeTanker),
	string(VehicleTypeDumpTruck),
	string(VehicleTypeSpecializedTruck),
	string(VehicleTypeLightTruck),
	string(VehicleTypeMediumTruck),
	string(VehicleTypeHeavyTruck),
}

// VehicleTypeNames returns a list of possible string values of VehicleType.
func VehicleTypeNames() []string {
	tmp := make([]string, len(_VehicleTypeNames))
	copy(tmp, _VehicleTypeNames)
	return tmp
}

// String implements the Stringer interface.
func (x VehicleType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x VehicleType) IsValid() bool {
	_, err := ParseVehicleType(string(x))
	return err == nil
}

var _VehicleTypeValue = map[string]VehicleType{
	"van":               VehicleTypeVan,
	"flatbed":           VehicleTypeFlatbed,
	"tanker":            VehicleTypeTanker,
	"dump_truck":        VehicleTypeDumpTruck,
	"specialized_truck": VehicleTypeSpecializedTruck,
	"light_truck":       VehicleTypeLightTruck,
	"medium_truck":      VehicleTypeMediumTruck,
	"heavy_truck":       VehicleTypeHeavyTruck,
}

// ParseVehicleType attempts to convert a string to a VehicleType.
func ParseVehicleType(name string) (VehicleType, error) {
	if x, ok := _VehicleTypeValue[name]; ok {
		return x, nil
	}
	return VehicleType(""), fmt.Errorf("%s is %w", name, ErrInvalidVehicleType)
}

func (x VehicleType) Ptr() *VehicleType {
	return &x
}

// MarshalText implements the text marshaller method.
func (x VehicleType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *VehicleType) UnmarshalText(text []byte) error {
	tmp, err := ParseVehicleType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *VehicleType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errVehicleTypeNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *VehicleType) Scan(value interface{}) (err error) {
	if value == nil {
		*x = VehicleType("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseVehicleType(v)
	case []byte:
		*x, err = ParseVehicleType(string(v))
	case VehicleType:
		*x = v
	case *VehicleType:
		if v == nil {
			return errVehicleTypeNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errVehicleTypeNilPtr
		}
		*x, err = ParseVehicleType(*v)
	default:
		return errors.New("invalid type for VehicleType")
	}

	return
}

// Value implements the driver Valuer interface.
func (x VehicleType) Value() (driver.Value, error) {
	return x.String(), nil
}
