// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package values

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// VehicleSubTypeDryVan is a VehicleSubType of type dry_van.
	VehicleSubTypeDryVan VehicleSubType = "dry_van"
	// VehicleSubTypeInsulated is a VehicleSubType of type insulated.
	VehicleSubTypeInsulated VehicleSubType = "insulated"
	// VehicleSubTypeRefrigerator is a VehicleSubType of type refrigerator.
	VehicleSubTypeRefrigerator VehicleSubType = "refrigerator"
	// VehicleSubTypeCurtainSide is a VehicleSubType of type curtain_side.
	VehicleSubTypeCurtainSide VehicleSubType = "curtain_side"
	// VehicleSubTypeBoxTruck is a VehicleSubType of type box_truck.
	VehicleSubTypeBoxTruck VehicleSubType = "box_truck"
	// VehicleSubTypeFurnitureVan is a VehicleSubType of type furniture_van.
	VehicleSubTypeFurnitureVan VehicleSubType = "furniture_van"
	// VehicleSubTypeStandardFlatbed is a VehicleSubType of type standard_flatbed.
	VehicleSubTypeStandardFlatbed VehicleSubType = "standard_flatbed"
	// VehicleSubTypeDropDeck is a VehicleSubType of type drop_deck.
	VehicleSubTypeDropDeck VehicleSubType = "drop_deck"
	// VehicleSubTypeLowboy is a VehicleSubType of type lowboy.
	VehicleSubTypeLowboy VehicleSubType = "lowboy"
	// VehicleSubTypeExtendable is a VehicleSubType of type extendable.
	VehicleSubTypeExtendable VehicleSubType = "extendable"
	// VehicleSubTypeConestoga is a VehicleSubType of type conestoga.
	VehicleSubTypeConestoga VehicleSubType = "conestoga"
	// VehicleSubTypeLiquidTanker is a VehicleSubType of type liquid_tanker.
	VehicleSubTypeLiquidTanker VehicleSubType = "liquid_tanker"
	// VehicleSubTypeGasTanker is a VehicleSubType of type gas_tanker.
	VehicleSubTypeGasTanker VehicleSubType = "gas_tanker"
	// VehicleSubTypeChemicalTanker is a VehicleSubType of type chemical_tanker.
	VehicleSubTypeChemicalTanker VehicleSubType = "chemical_tanker"
	// VehicleSubTypeFoodTanker is a VehicleSubType of type food_tanker.
	VehicleSubTypeFoodTanker VehicleSubType = "food_tanker"
	// VehicleSubTypeBitumenTanker is a VehicleSubType of type bitumen_tanker.
	VehicleSubTypeBitumenTanker VehicleSubType = "bitumen_tanker"
	// VehicleSubTypeRearDump is a VehicleSubType of type rear_dump.
	VehicleSubTypeRearDump VehicleSubType = "rear_dump"
	// VehicleSubTypeSideDump is a VehicleSubType of type side_dump.
	VehicleSubTypeSideDump VehicleSubType = "side_dump"
	// VehicleSubTypeBottomDump is a VehicleSubType of type bottom_dump.
	VehicleSubTypeBottomDump VehicleSubType = "bottom_dump"
	// VehicleSubTypeCarCarrier is a VehicleSubType of type car_carrier.
	VehicleSubTypeCarCarrier VehicleSubType = "car_carrier"
	// VehicleSubTypeTimberTruck is a VehicleSubType of type timber_truck.
	VehicleSubTypeTimberTruck VehicleSubType = "timber_truck"
	// VehicleSubTypeGrainTruck is a VehicleSubType of type grain_truck.
	VehicleSubTypeGrainTruck VehicleSubType = "grain_truck"
	// VehicleSubTypeLivestockCarrier is a VehicleSubType of type livestock_carrier.
	VehicleSubTypeLivestockCarrier VehicleSubType = "livestock_carrier"
	// VehicleSubTypeConcreteMixer is a VehicleSubType of type concrete_mixer.
	VehicleSubTypeConcreteMixer VehicleSubType = "concrete_mixer"
	// VehicleSubTypeContainerChassis is a VehicleSubType of type container_chassis.
	VehicleSubTypeContainerChassis VehicleSubType = "container_chassis"
	// VehicleSubTypeTowTruck is a VehicleSubType of type tow_truck.
	VehicleSubTypeTowTruck VehicleSubType = "tow_truck"
	// VehicleSubTypeCraneTruck is a VehicleSubType of type crane_truck.
	VehicleSubTypeCraneTruck VehicleSubType = "crane_truck"
	// VehicleSubTypeCityVan is a VehicleSubType of type city_van.
	VehicleSubTypeCityVan VehicleSubType = "city_van"
	// VehicleSubTypePickup is a VehicleSubType of type pickup.
	VehicleSubTypePickup VehicleSubType = "pickup"
	// VehicleSubTypeMinivanCargo is a VehicleSubType of type minivan_cargo.
	VehicleSubTypeMinivanCargo VehicleSubType = "minivan_cargo"
	// VehicleSubTypeMediumBox is a VehicleSubType of type medium_box.
	VehicleSubTypeMediumBox VehicleSubType = "medium_box"
	// VehicleSubTypeMediumFlatbed is a VehicleSubType of type medium_flatbed.
	VehicleSubTypeMediumFlatbed VehicleSubType = "medium_flatbed"
	// VehicleSubTypeSemiTrailer is a VehicleSubType of type semi_trailer.
	VehicleSubTypeSemiTrailer VehicleSubType = "semi_trailer"
	// VehicleSubTypeRoadTrain is a VehicleSubType of type road_train.
	VehicleSubTypeRoadTrain VehicleSubType = "road_train"
	// VehicleSubTypeMegaTrailer is a VehicleSubType of type mega_trailer.
	VehicleSubTypeMegaTrailer VehicleSubType = "mega_trailer"
)

var ErrInvalidVehicleSubType = fmt.Errorf("not a valid VehicleSubType, try [%s]", strings.Join(_VehicleSubTypeNames, ", "))

var _VehicleSubTypeNames = []string{
	string(VehicleSubTypeDryVan),
	string(VehicleSubTypeInsulated),
	string(VehicleSubTypeRefrigerator),
	string(VehicleSubTypeCurtainSide),
	string(VehicleSubTypeBoxTruck),
	string(VehicleSubTypeFurnitureVan),
	string(VehicleSubTypeStandardFlatbed),
	string(VehicleSubTypeDropDeck),
	string(VehicleSubTypeLowboy),
	string(VehicleSubTypeExtendable),
	string(VehicleSubTypeConestoga),
	string(VehicleSubTypeLiquidTanker),
	string(VehicleSubTypeGasTanker),
	string(VehicleSubTypeChemicalTanker),
	string(VehicleSubTypeFoodTanker),
	string(VehicleSubTypeBitumenTanker),
	string(VehicleSubTypeRearDump),
	string(VehicleSubTypeSideDump),
	string(VehicleSubTypeBottomDump),
	string(VehicleSubTypeCarCarrier),
	string(VehicleSubTypeTimberTruck),
	string(VehicleSubTypeGrainTruck),
	string(VehicleSubTypeLivestockCarrier),
	string(VehicleSubTypeConcreteMixer),
	string(VehicleSubTypeContainerChassis),
	string(VehicleSubTypeTowTruck),
	string(VehicleSubTypeCraneTruck),
	string(VehicleSubTypeCityVan),
	string(VehicleSubTypePickup),
	string(VehicleSubTypeMinivanCargo),
	string(VehicleSubTypeMediumBox),
	string(VehicleSubTypeMediumFlatbed),
	string(VehicleSubTypeSemiTrailer),
	string(VehicleSubTypeRoadTrain),
	string(VehicleSubTypeMegaTrailer),
}

// VehicleSubTypeNames returns a list of possible string values of VehicleSubType.
func VehicleSubTypeNames() []string {
	tmp := make([]string, len(_VehicleSubTypeNames))
	copy(tmp, _VehicleSubTypeNames)
	return tmp
}

// String implements the Stringer interface.
func (x VehicleSubType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x VehicleSubType) IsValid() bool {
	_, err := ParseVehicleSubType(string(x))
	return err == nil
}

var _VehicleSubTypeValue = map[string]VehicleSubType{
	"dry_van":           VehicleSubTypeDryVan,
	"insulated":         VehicleSubTypeInsulated,
	"refrigerator":      VehicleSubTypeRefrigerator,
	"curtain_side":      VehicleSubTypeCurtainSide,
	"box_truck":         VehicleSubTypeBoxTruck,
	"furniture_van":     VehicleSubTypeFurnitureVan,
	"standard_flatbed":  VehicleSubTypeStandardFlatbed,
	"drop_deck":         VehicleSubTypeDropDeck,
	"lowboy":            VehicleSubTypeLowboy,
	"extendable":        VehicleSubTypeExtendable,
	"conestoga":         VehicleSubTypeConestoga,
	"liquid_tanker":     VehicleSubTypeLiquidTanker,
	"gas_tanker":        VehicleSubTypeGasTanker,
	"chemical_tanker":   VehicleSubTypeChemicalTanker,
	"food_tanker":       VehicleSubTypeFoodTanker,
	"bitumen_tanker":    VehicleSubTypeBitumenTanker,
	"rear_dump":         VehicleSubTypeRearDump,
	"side_dump":         VehicleSubTypeSideDump,
	"bottom_dump":       VehicleSubTypeBottomDump,
	"car_carrier":       VehicleSubTypeCarCarrier,
	"timber_truck":      VehicleSubTypeTimberTruck,
	"grain_truck":       VehicleSubTypeGrainTruck,
	"livestock_carrier": VehicleSubTypeLivestockCarrier,
	"concrete_mixer":    VehicleSubTypeConcreteMixer,
	"container_chassis": VehicleSubTypeContainerChassis,
	"tow_truck":         VehicleSubTypeTowTruck,
	"crane_truck":       VehicleSubTypeCraneTruck,
	"city_van":          VehicleSubTypeCityVan,
	"pickup":            VehicleSubTypePickup,
	"minivan_cargo":     VehicleSubTypeMinivanCargo,
	"medium_box":        VehicleSubTypeMediumBox,
	"medium_flatbed":    VehicleSubTypeMediumFlatbed,
	"semi_trailer":      VehicleSubTypeSemiTrailer,
	"road_train":        VehicleSubTypeRoadTrain,
	"mega_trailer":      VehicleSubTypeMegaTrailer,
}

// ParseVehicleSubType attempts to convert a string to a VehicleSubType.
func ParseVehicleSubType(name string) (VehicleSubType, error) {
	if x, ok := _VehicleSubTypeValue[name]; ok {
		return x, nil
	}
	return VehicleSubType(""), fmt.Errorf("%s is %w", name, ErrInvalidVehicleSubType)
}

func (x VehicleSubType) Ptr() *VehicleSubType {
	return &x
}

// MarshalText implements the text marshaller method.
func (x VehicleSubType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *VehicleSubType) UnmarshalText(text []byte) error {
	tmp, err := ParseVehicleSubType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *VehicleSubType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errVehicleSubTypeNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *VehicleSubType) Scan(value interface{}) (err error) {
	if value == nil {
		*x = VehicleSubType("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseVehicleSubType(v)
	case []byte:
		*x, err = ParseVehicleSubType(string(v))
	case VehicleSubType:
		*x = v
	case *VehicleSubType:
		if v == nil {
			return errVehicleSubTypeNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errVehicleSubTypeNilPtr
		}
		*x, err = ParseVehicleSubType(*v)
	default:
		return errors.New("invalid type for VehicleSubType")
	}

	return
}

// Value implements the driver Valuer interface.
func (x VehicleSubType) Value() (driver.Value, error) {
	return x.String(), nil
}
